version: '3.5'

services:
  lascon2019:
    image: arunsectest/lascon2019
    container_name: lascon2019
    ports:
         - "80:80"
    healthcheck:
      # how often check should run (--interval), for how long (--timeout), and how many times (--retries) 
      test: "exit 0"
      interval: 30s
      timeout: 1m30s
      retries: 3
